# Bedrock Knowledge Base Resources
# Note: These resources are deployed in us-east-1 as bedrock is largely still unavailable in us-east-2

# Bedrock Knowledge Base
resource "aws_bedrockagent_knowledge_base" "concordia_cs340_bedrock_kb" {
  provider = aws.us_east_1

  name        = "concordia-cs340-kb"
  description = "KB for SE Class presentation"

  # IAM role permissions are defined in bedrock-iam.tf
  role_arn = aws_iam_role.concordia_cs340_bedrock_kb_role.arn

  knowledge_base_configuration {
    vector_knowledge_base_configuration {
      embedding_model_arn = "arn:aws:bedrock:us-east-1::foundation-model/amazon.titan-embed-text-v1"
      
      embedding_model_configuration {
        bedrock_embedding_model_configuration {
          embedding_data_type = "FLOAT32"
        }
      }
    }
    type = "VECTOR"
  }

  # TODO: Switch to S3_VECTORS when Terraform AWS Provider adds support - will need to recreate this KB though....
  # S3 Vectors is currently in preview and not yet fully supported in Terraform
  # Tracking issue: https://github.com/hashicorp/terraform-provider-aws/issues/43438
  # Expected configuration once supported:
  # storage_configuration {
  #   type = "S3_VECTORS"
  #   s3_vectors_configuration {
  #     # Vector ARN will be auto-generated by AWS when KB is created
  #     # For imports, would need to specify existing ARN:
  #     # vector_arn = "arn:aws:s3vectors:us-east-1:ACCOUNT_ID:bucket/BUCKET_NAME/index/INDEX_NAME"
  #   }
  # }

  # I omitted the actual opensearch serverless set up in terraform as it is a bit more complicated...
  storage_configuration {
    type = "OPENSEARCH_SERVERLESS"
    opensearch_serverless_configuration {
      collection_arn    = aws_opensearchserverless_collection.concordia_cs340_bedrock_kb_collection.arn
      vector_index_name = "bedrock-knowledge-base-default-index"
      field_mapping {
        vector_field   = "bedrock-knowledge-base-default-vector"
        text_field     = "AMAZON_BEDROCK_TEXT_CHUNK"
        metadata_field = "AMAZON_BEDROCK_METADATA"
      }
    }
  }

  tags = merge(local.common_tags, {
    Name = "concordia-cs340-kb"
  })
}

# Bedrock Knowledge Base Data Source - note the S3 bucket is declared in s3.tf
resource "aws_bedrockagent_data_source" "concordia_cs340_bedrock_kb_data_source" {
  provider = aws.us_east_1

  name = "concordia-cs340-kb-data-source"

  knowledge_base_id = aws_bedrockagent_knowledge_base.concordia_cs340_bedrock_kb.id
  
  data_source_configuration {
    type = "S3"
    
    s3_configuration {
      bucket_arn = aws_s3_bucket.concordia_cs340_bedrock_kb_data_source.arn
    }
  }

  data_deletion_policy = "DELETE"
}
